version: '3.8'
name: fluentpos

services:
  gateway:
    container_name: gateway
    image: iammukeshm/fluentpos.gateway:latest
    ports:
      - 7002:7002
      - 5002:5002
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - ASPNETCORE_URLS=https://+:7002;http://+:5002
      - ASPNETCORE_HTTPS_PORT=7002
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cert.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    networks:
     - fluentpos
  identity:
    container_name: identity
    image: iammukeshm/fluentpos.identity:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    depends_on:
      postgres:
        condition: service_healthy
    networks:
     - fluentpos
  catalog:
    container_name: catalog
    image: iammukeshm/fluentpos.catalog:latest
    depends_on:
      - mongo
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    networks:
     - fluentpos
  cart:
    container_name: cart
    image: iammukeshm/fluentpos.cart:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    networks:
     - fluentpos